var actors = [
    {
        id: 4515255,
        name: "Chris hemsworth",
        born: "11 August 1983",
        occupation: "Actor",
        height: 1.9,
        annual_income: 76.4,
        hometown: "Melbourne, Australia",
        from: "Phillip Island, Victoria, Australia",
        img: "https://iili.io/dUVeun.th.jpg",
    },
    {
        id: 4514555,
        name: "Jeson statham",
        born: "July 26, 1967",
        occupation: "Actor",
        height: 1.78,
        annual_income: 13,
        hometown: "Shirebrook, Derbyshire, England",
        from: "Shirebrook, United Kingdom",
        img: "https://iili.io/dUVUG4.th.jpg",
    },
    {
        id: 5514545,
        name: "Jeson statham",
        born: "April 23, 1977",
        occupation: "Actor, producer, director, screenwriter",
        height: 1.86,
        annual_income: 54,
        hometown: "Alameda County, California, United States",
        from: "California, United States",
        img: "https://iili.io/dUV6aS.th.jpg",
    },

    {
        id: 4614545,
        name: "Tom Hardy",
        born: "September 15, 1977",
        occupation: "Actor, producer, model",
        height: 1.75,
        annual_income: 54,
        hometown: "Hammersmith, London, United Kingdom",
        from: "London, United Kingdom",
        img: "https://iili.io/dUWI9t.th.jpg",
    },
    {
        id: 7714545,
        name: "Tom Cruise",
        born: "July 3, 1962",
        occupation: "Actor, producer",
        height: 1.7,
        annual_income: 25,
        hometown: "Syracuse, New York, United States",
        from: "New York, United States",
        img: "https://iili.io/dUWxSI.th.jpg",
    },
    {
        id: 8814545,
        name: "Robert Downey Jr.",
        born: "April 4, 1965",
        occupation: "Actor, producer, Singer",
        height: 1.74,
        annual_income: 75,
        hometown: "New York City, New York, U.S",
        from: "New York, United States",
        img: "https://iili.io/dUWYP4.th.jpg",
    },
    {
        id: 9814545,
        name: "Arnold Schwarzenegger",
        born: "July 30, 1947",
        occupation: "Actor, producer, Singer",
        height: 1.88,
        annual_income: 75,
        hometown: "Thal, Austria",
        from: "Thal, Austria",
        img: "https://iili.io/dUWll2.th.jpg",
    },
    {
        id: 1814545,
        name: "Sylvester Stallone",
        born: "July 6, 1946",
        occupation: "Actor, director, screenwriter, producer",
        height: 1.77,
        annual_income: 75,
        hometown: "Hell's Kitchen, New York, United States",
        from: "New York, United States",
        img: "https://iili.io/dUWjix.th.jpg",
    },
    {
        id: 1314545,
        name: "Dave Bautista",
        born: "January 18, 1969",
        occupation: "",
        height: 1.98,
        annual_income: 81,
        hometown: "Washington, D.C., United States",
        from: "Washington, D.C., United States",
        img: "https://iili.io/dUWNKQ.th.jpg",
    },
    {
        id: 1414545,
        name: "Dave Bautista",
        born: "January 18, 1969",
        occupation: "",
        height: 1.98,
        annual_income: 81,
        hometown: "Washington, D.C., United States",
        from: "Washington, D.C., United States",
        img: "https://iili.io/dUWNKQ.th.jpg",
    },
    {
        id: 1514545,
        name: "Dave Bautista",
        born: "January 18, 1969",
        occupation: "",
        height: 1.98,
        annual_income: 81,
        hometown: "Washington, D.C., United States",
        from: "Washington, D.C., United States",
        img: "https://iili.io/dUWNKQ.th.jpg",
    },

];

export default actors;